### ISSUE TITLE
Request for Method to Calculate se_cor

### ISSUE THREAD

**Issue by 1667857557** [ZhaotongL/cisMRcML#1]
Thanks for your excellent work. Could you provide the method for calculating _**se_cor**_? It wasn't included in the workflow.

**Comment by ZhaotongL** [comment]
> Thanks for your excellent work. Could you provide the method for calculating _**se_cor**_? It wasn't included in the workflow.

Hi, you may refer to the example used here to process the data: https://github.com/ZhaotongL/cisMR-paper/blob/main/process_ARIC.R#L86-L93.
