### ISSUE TITLE
The question about data preparing for cisMRcML

### ISSUE THREAD

**Issue by Y-Isaac** [ZhaotongL/cisMRcML#2]
Hi, it's really a nice tool, thanks for your effort!

I have successfully run the instance provided on vignette, however, I still have some uncertainties about how to obtain such data. I hope you can provide me with an answer:

1. Due to the differences in the list of SNPs contained in x_gwas, y_gwas, and LD panels in the real data, should I first extract the intersection of SNPs in these three datas?

2. If true, after extracting the intersection SNPs, should we further extract significant SNPs (such as 1e-6) and apply COJO to x_gwas and y_gwas respectively, and then extract the union of the two conditionally independent SNPs?

3.Is the minimum requirement for the number of instrumental variables IV-x>=3 and IV_y>=1?

Thanks for your help in advance!

Best regards

**Comment by ZhaotongL** [comment]
> Hi, it's really a nice tool, thanks for your effort!
> 
> I have successfully run the instance provided on vignette, however, I still have some uncertainties about how to obtain such data. I hope you can provide me with an answer:
> 
> 1. Due to the differences in the list of SNPs contained in x_gwas, y_gwas, and LD panels in the real data, should I first extract the intersection of SNPs in these three datas?
> 2. If true, after extracting the intersection SNPs, should we further extract significant SNPs (such as 1e-6) and apply COJO to x_gwas and y_gwas respectively, and then extract the union of the two conditionally independent SNPs?
> 
> 3.Is the minimum requirement for the number of instrumental variables IV-x>=3 and IV_y>=1?
> 
> Thanks for your help in advance!
> 
> Best regards

1. Yes, to maximize the overlapped SNP set, you can first try to impute your GWAS dataset first.
2. No, you don't need to do the filtering.
3. No requirement on the number of SNPs associated with Y identified by COJO. And IV-X>=3 so that we can apply the robust cML method. Or you can also set K_vec=0 to ASSUME all IVs are valid if you only have 2 IVs associated with X.

**Comment by Y-Isaac** [comment]
> > Hi, it's really a nice tool, thanks for your effort!
> > I have successfully run the instance provided on vignette, however, I still have some uncertainties about how to obtain such data. I hope you can provide me with an answer:
> > 
> > 1. Due to the differences in the list of SNPs contained in x_gwas, y_gwas, and LD panels in the real data, should I first extract the intersection of SNPs in these three datas?
> > 2. If true, after extracting the intersection SNPs, should we further extract significant SNPs (such as 1e-6) and apply COJO to x_gwas and y_gwas respectively, and then extract the union of the two conditionally independent SNPs?
> > 
> > 3.Is the minimum requirement for the number of instrumental variables IV-x>=3 and IV_y>=1?
> > Thanks for your help in advance!
> > Best regards
> 
> 1. Yes, to maximize the overlapped SNP set, you can first try to impute your GWAS dataset first.
> 2. No, you don't need to do the filtering.
> 3. No requirement on the number of SNPs associated with Y identified by COJO. And IV-X>=3 so that we can apply the robust cML method. Or you can also set K_vec=0 to ASSUME all IVs are valid if you only have 2 IVs associated with X.

Thannnnnks!
