### ISSUE TITLE
How to run 

### ISSUE THREAD

**Issue by jielab** [ZhaotongL/cisMRcML#3]
Dear Dr. Lin:

This https://rpubs.com/ZhaotongL/cisMRcML_vignette seems quite easy to understand. Thanks!

However, my **exp_df** and **out_df** do NOT have  **cor** and **cor_se**. The above tutorial only showed how to calculate **cor**, but not how to calculate **cor_se**. Then, how could I calcualte **bJ**? Do I must run **GCTA-COJO** first?

Also, I could calculate the **LD_mat** from PLINK. Is there an easy way to export PLINK output into R?

Anyway, a more detailed tutorial example with exact steps to prepare the data would be great for readers of your wonderful software.

BTW, did you guys compare your method with TwoStepCisMR (https://www.mdpi.com/2073-4425/13/9/1541), which was published in 2022?

Best regards,
Jie

**Comment by ZhaotongL** [comment]
> Dear Dr. Lin:
> 
> This https://rpubs.com/ZhaotongL/cisMRcML_vignette seems quite easy to understand. Thanks!
> 
> However, my **exp_df** and **out_df** do NOT have **cor** and **cor_se**. The above tutorial only showed how to calculate **cor**, but not how to calculate **cor_se**. Then, how could I calcualte **bJ**? Do I must run **GCTA-COJO** first?
> 
> Also, I could calculate the **LD_mat** from PLINK. Is there an easy way to export PLINK output into R?
> 
> Anyway, a more detailed tutorial example with exact steps to prepare the data would be great for readers of your wonderful software.
> 
> BTW, did you guys compare your method with TwoStepCisMR (https://www.mdpi.com/2073-4425/13/9/1541), which was published in 2022?
> 
> Best regards, Jie

Hi Jie,

Yes, you need to run COJO (or other similar methods) to select SNPs jointly associated with the exposure, and SNPs jointly associated with the outcome (this is for adjusting for LD-induced pleiotropy). You may refer to the example used here to process the data: https://github.com/ZhaotongL/cisMR-paper/blob/main/process_ARIC.R. We didn't compare with TwoStepCisMR, but compared with other approaches such as generalized-IVW and generalized-Egger regression.

Best,
Zhaotong

**Comment by jielab** [comment]
Thanks, Dr. Lin!

For your script, shown as below, **pqtl** means the GWAS for protein level while **gwas** means the GWAS for the output trait, correct? 

Previously, I thought that **QTL only refers to those significant loci**, not genome-wide summary statistics, for millions of SNPs.
 
![image](https://github.com/user-attachments/assets/578571eb-796c-4225-a255-fa6391c25ad0)

Best regards,
Jie

**Comment by ZhaotongL** [comment]
> Thanks, Dr. Lin!
> 
> For your script, shown as below, **pqtl** means the GWAS for protein level while **gwas** means the GWAS for the output trait, correct?
> 
> Previously, I thought that **QTL only refers to those significant loci**, not genome-wide summary statistics, for millions of SNPs.
> 
> ![image](https://private-user-images.githubusercontent.com/26947455/386808629-578571eb-796c-4225-a255-fa6391c25ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwMzU4MDksIm5iZiI6MTczMjAzNTUwOSwicGF0aCI6Ii8yNjk0NzQ1NS8zODY4MDg2MjktNTc4NTcxZWItNzk2Yy00MjI1LWEyNTUtZmE2MzkxYzI1YWQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE5VDE2NTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MDQ4NGJiNDdmNWI5Y2IyMjQ2ZDllODY1Y2M3YzI0NjAyODRmNjk0NjEyZDRlODQ3MDNlOTQxYmI5MjMyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KmLLRbzHxPYvQoHEMt9ENC4ZVf3YRsZDmEIIV0paEWs)
> 
> Best regards, Jie

Hi Jie,

The screenshot you provided is only for extracting the common SNPs in both pQTL and GWAS datasets for downstream data processing, not the set of IVs in the final analysis. In L86, we extracted significant pQTLs as IVs. And as discussed in the manuscript, we also included outcome-associated SNPs in the analysis to account for LD-induced pleiotropy.
