### ISSUE TITLE
Is cisMRcML MR or colocalization?

### ISSUE THREAD

**Issue by jielab** [ZhaotongL/cisMRcML#4]
Hi, there:

I found that the l**east significant P-value** of  your example data mr_dat$**exp_df** is 4.2308e-09. Does this means that all SNPs included in exp_df must be genome-wide significant?

Previously I thought that cisMRcML is like a **coloc** analysis, where non-significant SNPs are included. So, should I run coloc after running cisMRcML?

Thanks!
JH

**Comment by ZhaotongL** [comment]
> Hi, there:
> 
> I found that the l**east significant P-value** of your example data mr_dat$**exp_df** is 4.2308e-09. Does this means that all SNPs included in exp_df must be genome-wide significant?
> 
> Previously I thought that cisMRcML is like a **coloc** analysis, where non-significant SNPs are included. So, should I run coloc after running cisMRcML?
> 
> Thanks! JH

Hi Jie,

Thank you for your interest! 

cisMR-cML is an MR method, which uses cis-SNPs around the gene of interest as instrumental variables. It is not a colocalization method. In our manuscript, we ran colocalization after cisMR to evaluate our findings from the cisMR analysis.

**Comment by jielab** [comment]
Thanks, Dr. Lin!

**cisMR-cML** only includes SNPs whose _P_ <5E-08, while **colocalization** needs to include all significant and non-significant SNPs, correct? For cis-pQTL, usually there are not many SNPs with _P_ <5E-08, do you think it is better to change this threshold to something like _P_ <5E-05?

Your paper said that **we identified three potential drug targets, PCSK9, COLEC11 and FGFR1 for CAD**. But the biggest drug target for CAD is **HMG-CoA reductase**. Somehow your analysis could not pick up this protein?

Your colocalization analysis only provided causal evidence for PCSK9, COLEC11, but not for FGFR1. What is the potential reason for this? Frankly, I have no confidence with colocalization analysis, even though every paper reports colocalization analysis after running MR.  For example, colocalization analysis with eQTL data is actually fake data, because the eQTL is imputed from GTeX and no eQTL of study participants was actually measured.

Best regards,
Jie

**Comment by ZhaotongL** [comment]
> Thanks, Dr. Lin!
> 
> **cisMR-cML** only includes SNPs whose _P_ <5E-08, while **colocalization** needs to include all significant and non-significant SNPs, correct? For cis-pQTL, usually there are not many SNPs with _P_ <5E-08, do you think it is better to change this threshold to something like _P_ <5E-05?
> 
> Your paper said that **we identified three potential drug targets, PCSK9, COLEC11 and FGFR1 for CAD**. But the biggest drug target for CAD is **HMG-CoA reductase**. Somehow your analysis could not pick up this protein?
> 
> Your colocalization analysis only provided causal evidence for PCSK9, COLEC11, but not for FGFR1. What is the potential reason for this? Frankly, I have no confidence with colocalization analysis, even though every paper reports colocalization analysis after running MR. For example, colocalization analysis with eQTL data is actually fake data, because the eQTL is imputed from GTeX and no eQTL of study participants was actually measured.
> 
> Best regards, Jie

Hi Jie,

In our manuscript, we used 5e-6 as the threshold in the COJO analysis. There is a tradeoff between using more or less stringent thresholds in the analysis, which is discussed in the paper and we also compared the different choices of threshold in the supplementary. 

For the protein HMGCR you mentioned, we didn't pick it up mainly because we didn't find any significant pQTL associated with it in the ARIC dataset we used. 

We have briefly discussed the relationship between colocalization and cisMR in the manuscript. For a more detailed discussion, please refer to https://pubmed.ncbi.nlm.nih.gov/35452592/.

Best,
Zhaotong
